### ISSUE TITLE
Project enhancement

### ISSUE THREAD

**Issue by catalinmiron** [Kemcake/parse-react-sample#1]
Hi @Kemcake,

This is a great project, from a starter kit perspective. What I'd like to bring into this starter kit are the following:

Remove:
- jest ( damn sllow)
- browserify
- gulp

Add:
- webpack
- babel
- mocha, chai, instanbul
- eslint
- sass, less loaders

To give you a little preview of the enhancement, please take a look at the following gif.

![parse-webpack-starter-kit-v3](https://cloud.githubusercontent.com/assets/2805320/10178736/3996c9e0-670a-11e5-8fa8-de0996476f20.gif)

**Comment by Kemcake** [comment]
Hello @catalinmiron!

**Comment by remstos** [comment]
Hello @catalinmiron 
I agree that this repo starts to become a bit old and could be improved by replacing some parts
I would love to see what you did!

I was also thinking about rewriting it with ES6, what do you think of this ?

**Comment by catalinmiron** [comment]
Yes, I forgot to mention about ES6 syntax.

Good to know that, when using ES6, there are no mixins available. But Parse made a wrapper called [ParseComponent](https://github.com/ParsePlatform/ParseReact/blob/master/docs/api/ES6.md) for React.Component. I'll push my changes with the webpack implementation and we'll figure a way of making this happen :)

I'd also like to move the tests from jest to a performant branch, as mocha / chai are. So, I'm going to make another PR where I'll do this, what do you think?

PS: Right now I don't have access to the changes since I'm at ~~office~~ work, but as soon as I'll be at home I'll push the changes.

Can you think about a future roadmap? Where this project should go? What are the future improvements? Can we make a `yeoman` generator out of it?

**Comment by catalinmiron** [comment]
@Kemcake you can check the changes in the PR (https://github.com/Kemcake/parse-react-sample/pull/2)
